namespace FinalProject.Domain.Enums
{
    public enum ProjectCategories
    {
        Entertainment = 1,
        SocialNetwork = 2,
        Education = 3,
        Commerce = 4,
        Charity = 5,
        HealthAndFitness = 6,
        Travel = 7,
        FoodAndDrink = 8,
        Technology = 9,
        Sports = 10,
        Finance = 11,
        RealEstate = 12,
        NewsAndMedia = 13,
        PersonalDevelopment = 14,
        Fashion = 15,
        Beauty = 16,
        Parenting = 17,
        Pets = 18,
        ArtsAndCulture = 19,
        Automotive = 20,
        Music = 21,
        Photography = 22,
        Games = 23,
        Environment = 24,
        Science = 25,
        Weather = 26,
        Events = 27,
        Dating = 28,
        Shopping = 29,
        NonProfit = 30,
        Government = 31,
        JobSearch = 32,
        HomeAndGarden = 33,
        Books = 34,
        Movies = 35,
        TVShows = 36,
        OnlineCourses = 37,
        Recipes = 38,
        Reviews = 39,
        History = 40,
        Transportation = 41,
        Agriculture = 42,
        Industry = 43,
        Logistics = 44,
        Advertising = 45,
        HumanResources = 46,
        Manufacturing = 47,
    }
}